repos:
  - repo: local
    rev: 0.0.0
    hooks:
      - id: mypy-pre-push
        name: mypy (pre-push)
        entry: mypy
        args: [app]
        language: system
        pass_filenames: false
        stages: [pre-push]
